config/routes.rb
Rails.application.routes.draw do
  #1st step: start a new project in Terminal
  #2nd step: create a new controller for your first model
  #3rd step: set up URLs/Routes in Code editor
  #4th add root of index

  resources :categories

  root "categories#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(form_params)

    @category.save

    redirect_to root_path
  end

  def show
    @category = Category.find(params[:id])
  end

  def form_params
    params.require(:category).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <%= f.submit "Save category" %>
<% end %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <div class="category">
    <%= link_to category.title, category_path(category) %>
  </div>

<% end %>

app/views/categories/new.html.erb
<h3>Add a new category</h3>

<%= render "form" %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Craigslist Copy - This is a great Craigslist copy site for different services</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1><%= link_to "Craigslist Copy", root_path %></h1>

      <h2>This is a great Craigslist copy site for different services<h2>
      <nav>
        <%= link_to "Add a category", new_category_path %>
      </nav>
    </header>

    <%= yield %>

    <footer>
      Copyright 2020 Simon Laubscher
    </footer>
  </body>
</html>